auth_enabled: false

storage_config:
    boltdb:
        directory: /data/loki/index

ingester:
    lifecycler:
        address: 0.0.0.0:3100
        ring:
            kvstore:
                store: inmemory
            replication_factor: 1
        final_sleep: 0s

schema_config:
    configs:
        - from: 2021-01-15
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
              prefix: index_
              period: 48h

compactor:
    working_directory: /tmp/loki/compactor
    shared_store: filesystem
    shared_storage_options:
        filesystem:
            directory: /data/loki/chunks

limits_config:
    reject_old_samples: true
    reject_old_samples_max_age: 168h

chunk_store_config:
    max_look_back_period: 0s

table_manager:
    retention_deletes_enabled: false
    retention_period: 0s
